version: '3.4'
volumes: 
  mongodbdata:

services:
  outrageousmongo:
    image: 'mongo:latest'
    build: ./mongo
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/mongo:ro
      - mongodbdata:/data/db
    ports:
      - '27017:27017'
  outrageousexpress:
    image: 'node:latest'
    working_dir: /express
    ports: 
     - '1300:1300'
    volumes: 
      - './express:/express'
    command: bash -c "npm install && npm start"
